[('inventoryID', '^[0-9]{4}$'), 
('deviceName', '^(?!\\s*$).+'), 
('osVer', '^\\d+(\\.\\d+)*$'), 
('resolution', '^\\d{3,4}x\\d{3,4}'), 
('resolutionWithoutNB', '^\\d{3,4}x\\d{3,4}'), 
('aspectRatio', '^\\d+(\\.\\d)?:\\d+$'), 
('hardwareKeyTest', '^[A-Za-z0-9]{8}-([A-Za-z0-9]{4}-){3}[A-Za-z0-9]{20}-([A-Za-z0-9]{4}-){3}[A-Za-z0-9]{4}$'), 
('deviceInfoAndroid', '^[A-Za-z0-9]{14,16}$'), 
('macAddress', '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')]